[project]
name = "apple-leaf-disease"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=5.0.1",
    "mysql-connector-python>=9.3.0",
]
